language: python
python: "2.7"

sudo: required

env:
  - image: ubuntu
    tag: 14.04
    init: /sbin/init
    run_opts: ""
  - image: photon
    tag: latest
    init:
    run_opts: ""


services:
  - docker

before_install:
  - sudo docker pull ${image}:${tag}
  - sudo docker build --rm=true --file=tests/dockerfiles/${image}-${tag} -t ${image}:local .

install:
  - container_id=$(mktemp)
  - pwd
  - ls -al
  - sudo docker run --detach --volume=$(pwd):/etc/ansible/roles/ansible:ro ${run_opts} ${image}:local ${init} > "${container_id}"

script:
  - docker ps
  - docker logs "$(cat ${container_id})"
  - docker inspect "$(cat ${container_id})"
  - sudo docker exec --tty "$(cat ${container_id})" env TERM=xterm find /etc/ansible
  - sudo docker exec --tty "$(cat ${container_id})" env TERM=xterm /usr/bin/ansible-playbook /etc/ansible/roles/ansible/tests/test.yml --syntax-check
  - sudo docker exec --tty "$(cat ${container_id})" env TERM=xterm /usr/bin/ansible-playbook /etc/ansible/roles/ansible/tests/test.yml
# re-run test and check for no change
# note that we're expecting one change to happen.
# the libxslt-dev package is virtual, and appears to change every time.
# when bug is fixed, this will start failing.  Change 1 to 0 below.
# see bug at: https://github.com/ansible/ansible-modules-core/pull/1348
  - >
    sudo docker exec "$(cat ${container_id})" /usr/bin/ansible-playbook /etc/ansible/roles/role_under_test/tests/test.yml
    | grep -q 'changed=1.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)
