language: python
python: "2.7"

sudo: required

env:
  - image: ubuntu
    tag: 14.04
    init: /sbin/init
    run_opts: ""
  - image: photon
    tag: latest
    init: /sbin/init
    run_opts: ""


services:
  - docker

before_install:
# our repo directory structure doesn't match our role name
# rename the cloned dir so that tests pass
# within repo and within travis.
  - mv ../ansible-role-ansible ../ansible
  - sudo docker pull ${image}:${tag}
  - sudo docker build --rm=true --file=tests/dockerfiles/${image}-${tag} -t ${image}-${tag}:local

install:
  - container_id=$(mktemp)
  - sudo docker run --detach --volume="${PWD}":/etc/ansible/roles/role_under_test:ro ${run_opts} ${image}:${tag} "${init}" > "${container_id}"

script:
  - sudo docker exec --tty "$(cat ${container_id})" env TERM=xterm ansible-playbook /etc/ansible/roles/role_under_test/tests/test.yml --syntax-check
  - sudo docker exec --tty "$(cat ${container_id})" env TERM=xterm ansible-playbook /etc/ansible/roles/role_under_test/tests/test.yml
# re-run test and check for no change
# note that we're expecting one change to happen.
# the libxslt-dev package is virtual, and appears to change every time.
# when bug is fixed, this will start failing.  Change 1 to 0 below.
# see bug at: https://github.com/ansible/ansible-modules-core/pull/1348
  - >
    sudo docker exec "$(cat ${container_id})" ansible-playbook /etc/ansible/roles/role_under_test/tests/test.yml
    | grep -q 'changed=1.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)

